### ISSUE TITLE
Feature Request: Ollama Support

### ISSUE THREAD

**Issue by la3rence** [LiangWei88/xExtension-ArticleSummary#1]
Wonderful extension for FreshRSS!

Currently I've tried with my Ollama endpoint without any API key input - obviously it failed to fetch response:

<img width="1304" alt="Screenshot 2024-11-25 at 23 42 51" src="https://github.com/user-attachments/assets/dec5ca40-e842-4d87-bb44-c9378ea22fdb">

It would be pretty nice if it can support Ollama which is a most popular solution for self-hosted LLMs.
Thanks a lot.

Reference Docs: https://github.com/ollama/ollama/blob/main/docs/api.md#generate-a-completion

**Comment by LiangWei88** [comment]
Interesting requirement, I've also used quite a few ollama before. Since discovering free APIs online, I've been using them ever since. However, ollama is indeed a great AI API solution, and I'll find time to modify this extension to support ollama. But it may be next week before I have the time. If you want to modify this extension, you can also submit a PR. Thank you very much for liking my extension. If you like it, you can give it a star, too
